"""
Planning result data structure for Procela.

This module defines the `PlanningResult` dataclass, which captures
the outcome of a planning task. It contains proposed actions,
recommended selections, associated confidence, strategy metadata,
and a timestamp marking the planning execution.

Semantics Reference
-------------------
https://procela.org/docs/semantics/core/assessment/planning.html

Examples Reference
------------------
https://procela.org/docs/examples/core/assessment/planning.html
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass(frozen=True, slots=True)
class PlanningResult:
    """
    Outcome of a planning task, including proposals and recommendations.

    Parameters
    ----------
    proposals : list[Any]
        List of all candidate action proposals generated by the planner.
    recommended : list[Any] | None, optional
        Subset of `proposals` recommended for execution. Defaults to None.
    confidence : float | None, optional
        Confidence level in the recommended actions (0.0, 1.0). Defaults to None.
    strategy : str | None, optional
        Strategy description or identifier used to generate proposals.
        Defaults to None.
    metadata : dict[str, Any], optional
        Arbitrary metadata associated with the planning result.
        Defaults to empty dict.
    timestamp : datetime, optional
        UTC-aware timestamp marking the planning execution.
        Defaults to current time.

    Notes
    -----
    - `recommended` proposals must be a subset of `proposals`.
    - `confidence` is validated to be between 0.0 and 1.0.
    - `timestamp` is automatically converted to UTC if not timezone-aware.
    """

    proposals: list[Any]
    recommended: list[Any] | None = None
    confidence: float | None = None
    strategy: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def __post_init__(self) -> None:
        """
        Validate proposals, recommended subset, confidence, and timestamp.

        Raises
        ------
        TypeError
            If `proposals` is not a list, `recommended` is not a list or None,
            or `confidence` is not a number.
        ValueError
            If any recommended proposal is not in `proposals`,
            or `confidence` is outside 0.0 - 1.0 range.
        """
        # Validate proposals type and content
        if not isinstance(self.proposals, list):
            raise TypeError(
                "Proposals must be a list, " f"got {type(self.proposals).__name__}"
            )

        # Validate that all recommended proposals are in proposals
        if self.recommended is not None:
            if not isinstance(self.recommended, list):
                raise TypeError(
                    "Recommended must be a list or None, "
                    f"got {type(self.recommended).__name__}"
                )
            for rec in self.recommended:
                if rec not in self.proposals:
                    raise ValueError(
                        f"Recommended proposal {rec} is not in the proposals list"
                    )

        # Validate confidence range
        if self.confidence is not None:
            if not isinstance(self.confidence, int | float):
                raise TypeError(
                    "Confidence must be int or float, "
                    f"got {type(self.confidence).__name__}"
                )
            if not 0.0 <= self.confidence <= 1.0:
                raise ValueError(
                    f"Confidence must be between 0.0 and 1.0, got {self.confidence}"
                )

        # Ensure timestamp is timezone-aware
        if self.timestamp.tzinfo is None:
            object.__setattr__(
                self, "timestamp", self.timestamp.replace(tzinfo=timezone.utc)
            )
