"""
Proposal module for the Procela framework.

This module defines the core ActionProposal class and its associated status
enumeration. Action proposals are intelligent reasoning entities that represent
suggested state transformations within Procela's active reasoning engine.
They encapsulate the what, why, and with-what-certainty of potential actions.

Semantics Reference
-------------------
https://procela.org/docs/semantics/core/action/proposal.html

Examples Reference
-------------------
https://procela.org/docs/examples/core/action/proposal.html
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from ...symbols.key import Key
from .effect import ActionEffect


class ProposalStatus(Enum):
    """
    Enumeration representing the lifecycle states of an ActionProposal.

    Proposals transition through these states as they are evaluated, selected,
    and executed by the Procela reasoning engine. Each state represents a
    specific phase in the proposal's contractual agreement with the system.

    Attributes
    ----------
    PROPOSED : str
        Initial state. The proposal has been generated by a reasoning entity
        and is awaiting validation.
    VALIDATED : str
        The proposal has passed initial system constraint checks and is
        eligible for selection.
    SELECTED : str
        The proposal has been chosen by a `SelectionPolicy` as the next
        action to execute.
    EXECUTING : str
        The action associated with the proposal is currently being applied
        to the system state.
    COMPLETED : str
        The action has finished successfully, and its effects have been
        integrated into the system state.
    REJECTED : str
        The proposal failed validation or was explicitly rejected by a policy.
        It will not be executed.
    CANCELED : str
        The proposal was valid and possibly selected, but was canceled
        before or during execution due to changing system conditions.
    """

    PROPOSED = "proposed"
    VALIDATED = "validated"
    SELECTED = "selected"
    EXECUTING = "executing"
    COMPLETED = "completed"
    REJECTED = "rejected"
    CANCELED = "canceled"


@dataclass(frozen=True)
class ActionProposal:
    """
    A frozen, immutable data entity representing a proposed system action.

    This is a core intelligent entity in Procela. It is not merely a data
    container but an active participant in the reasoning process. Each proposal
    carries its own confidence, rationale, predicted effect, and tracks its
    lifecycle status, enabling decentralized decision-making and audit trails.

    Parameters
    ----------
    value : Any
        The core content or target value of the proposal. This is often a
        new state, a delta/change, or a command. Type is flexible to
        accommodate diverse system domains (e.g., float, dict, custom object).
    confidence : float
        A quantitative measure of certainty in the proposal's suitability,
        typically in the range [0.0, 1.0]. Can be used by policies for selection.
    source : Key | None, optional
        The identifier (Key) of the reasoning entity (e.g., a `Variable`)
        that generated this proposal. Enables traceability and feedback loops.
        Default is None.
    action : str | None, optional
        A descriptor or name of the type of action being proposed
        (e.g., "increment", "set", "repair"). Default is None.
    rationale : str | None, optional
        A human and machine-readable explanation of *why* this proposal was
        generated. Critical for explainability and debugging. Default is None.
    effect : ActionEffect | None, optional
        The predicted outcome (`ActionEffect`) of executing this proposal.
        Links causal prediction to action. Default is None.
    metadata : dict[str, Any] | None, optional
        A flexible dictionary for additional domain-specific data,
        constraints, or provenance information. Default is None.
    timestamp : datetime, optional
        The UTC datetime when this proposal instance was created. Managed
        automatically via `default_factory`. Defaults to `datetime.now(timezone.utc)`.
    status : ProposalStatus, optional
        The current lifecycle state of the proposal. Defaults to
        `ProposalStatus.PROPOSED`.

    Attributes
    ----------
    value : Any
        See Parameters section.
    confidence : float
        See Parameters section.
    source : Key | None
        See Parameters section.
    action : str | None
        See Parameters section.
    rationale : str | None
        See Parameters section.
    effect : ActionEffect | None
        See Parameters section.
    metadata : dict[str, Any] | None
        See Parameters section.
    timestamp : datetime
        See Parameters section.
    status : ProposalStatus
        See Parameters section.

    Raises
    ------
    ValueError
        If `confidence` is not a float or is outside the logical range [0.0, 1.0].
    TypeError
        If provided `timestamp` is not a `datetime` object, or `status` is not
        a `ProposalStatus` instance.

    Notes
    -----
    This is a frozen (`frozen=True`) dataclass. Instances are immutable after
    creation, ensuring consistent state for reasoning. New states are created
    via the `with_status` method or by constructing new instances. Immutability
    is key for safe caching, hashing, and use in concurrent contexts.
    """

    value: Any
    confidence: float | None = None
    source: Key | None = None
    action: str | None = None
    rationale: str | None = None
    effect: ActionEffect | None = None
    metadata: dict[str, Any] | None = None
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    status: ProposalStatus = ProposalStatus.PROPOSED

    def __post_init__(self) -> None:
        """
        Validate the dataclass fields after initialization.

        Automatically called by the dataclass machinery. Enforces Procela's
        contractual guarantees for proposal validity.

        Raises
        ------
        ValueError
            If `confidence` is not between 0.0 and 1.0 inclusive.
        TypeError
            If `timestamp` is not a `datetime` object or `status` is not a
            `ProposalStatus` instance.
        """
        # Validate confidence range
        if self.confidence and not isinstance(self.confidence, (int, float)):
            raise TypeError(
                f"Confidence must be int or float, "
                f"got {type(self.confidence).__name__}"
            )
        if self.confidence and not 0.0 <= self.confidence <= 1.0:
            raise ValueError(
                f"Confidence must be between 0.0 and 1.0, " f"got {self.confidence}"
            )

        # Validate timestamp type
        if not isinstance(self.timestamp, datetime):
            raise TypeError(
                f"Timestamp must be a datetime object, "
                f"got {type(self.timestamp).__name__}"
            )

        # Validate status type
        if not isinstance(self.status, ProposalStatus):
            raise TypeError(
                f"Status must be a ProposalStatus enum, "
                f"got {type(self.status).__name__}"
            )

        # Ensure timestamp is timezone-aware (preferably UTC)
        if self.timestamp.tzinfo is None:
            # This is a simplification; a warning might be raised or error
            # For strictness, ValueError could be raised
            object.__setattr__(
                self, "timestamp", self.timestamp.replace(tzinfo=timezone.utc)
            )

    def with_status(self, status: ProposalStatus) -> ActionProposal:
        """
        Create a new ActionProposal with an updated status.

        This is the primary method for progressing a proposal through its
        lifecycle. Because the class is frozen, this method returns a *new*
        instance with all fields identical except the `status`. This preserves
        immutability while enabling state transitions.

        Parameters
        ----------
        status : ProposalStatus
            The new status for the proposal.

        Returns
        -------
        ActionProposal
            A new, immutable `ActionProposal` instance with the specified status
            and all other fields copied from `self`.

        Raises
        ------
        TypeError
            If the provided `status` is not a `ProposalStatus` instance.
        """
        if not isinstance(status, ProposalStatus):
            raise TypeError(
                f"Status must be a ProposalStatus enum, " f"got {type(status).__name__}"
            )

        # Return a new instance with the updated status
        return ActionProposal(
            value=self.value,
            confidence=self.confidence,
            source=self.source,
            action=self.action,
            rationale=self.rationale,
            effect=self.effect,
            metadata=self.metadata,
            timestamp=self.timestamp,
            status=status,
        )
